# -*- MakeFile -*-

chacha20: chacha20.o quarter_round.o state_init.o permute_state.o encrypt.o run_test.o calculate_throughput.o
	gcc chacha20.o quarter_round.o state_init.o permute_state.o encrypt.o run_test.o calculate_throughput.o -O3 -o chacha20

chacha20.o: chacha20.c
	gcc -c chacha20.c

quarter_round.o: quarter_round.c
	gcc -c quarter_round.c

state_init.o: state_init.c
	gcc -c state_init.c

permute_state.o: permute_state.c
	gcc -c permute_state.c

encrypt.o: encrypt.c
	gcc -c encrypt.c

run_test.o: run_test.c
	gcc -c run_test.c

calculate_throughput.o: calculate_throughput.c
	gcc -c calculate_throughput.c

clean: # Used to remove all files generated by the build process.
	cmd /C del /Q chacha20.exe chacha20.o quarter_round.o state_init.o permute_state.o encrypt.o run_test.o calculate_throughput.o

.PHONY: clean # This tells make that clean is not a file, but a command.make 