name: Windows Environment Execution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering

jobs:
  run-on-windows:
    runs-on: windows-latest

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up environment
      - name: Set up environment
        run: |
          choco install mingw -y # Install MinGW for GCC
          refreshenv # Refresh environment variables

      # Build the project
      - name: Build the project
        run: |
          mingw32-make # Use MinGW's make command

      # Run your application
      - name: Run the application
        run: |
          ./chacha20 --enc-tv
