name: Windows Environment Execution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install MinGW
      run: |
        choco install mingw -y

    - name: Add MinGW to PATH
      run: |
        setx PATH "%PATH%;C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin"

    - name: Verify MinGW Installation
      run: |
        gcc --version
        mingw32-make --version

    - name: Configure the Build
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release -G "MinGW Makefiles"

    - name: Build the Project
      run: |
        cmake --build build --config Release


    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: build
        if-no-files-found: error

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v3
      with:
        name: build-artifact
        path: .

    - name: Configure GitHub Pages
      uses: actions/configure-pages@v1

    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: build

    - id: deployment
      name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
